name: remote ssh command
on: 
  schedule:
    - cron: '* * * * *'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
       run： |
        echo "pass"
